# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetitle', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=7)),
            ],
        ),
    ]
